### ISSUE TITLE
Discord api types

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord-utils-bot#106]
Add API types command ( like docs )

**Comment by megatank58** [comment]
This does not seem that easy (or possible), the discord-api-types uses this package https://www.npmjs.com/package/docusaurus-plugin-typedoc-api to actually parse the docs from the ts files directly and output custom react styled pages, a solution could be to output a JSON with a GitHub workflow everytime a release is made (similar to how the current discord.js workflows work) but that will require it to be there in the discord-api-types repository

**Comment by JPBM135** [comment]
This is likely to be implemented when the new site gets finished!
