### ISSUE TITLE
Link escape not working correctly

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord-utils-bot#111]
![image](https://user-images.githubusercontent.com/26532370/180651731-7cc7d98e-5164-4ef7-9188-5bcd6a0ca662.png)

**Comment by JPBM135** [comment]
I see two ways to solve this:

- If the bot does not use any embeds whatsoever, just set the `supressEmbeds` flag

- Use an regex to match any unescaped url and escape it like: `replace(/[^<](linkrgx)[^>]/, '<$1>')`

**Comment by almostSouji** [comment]
variant
![image](https://user-images.githubusercontent.com/26532370/189647886-ce47e968-6f4f-4787-b9ba-2cb5cefd1637.png)
