### ISSUE TITLE
Feature: Autocomplete for node docs

### ISSUE THREAD

**Issue by JPBM135** [discordjs/discord-utils-bot#122]
Use an approach inspired by the `discordjs-docs-parser` by Favna, we could create our own search engine using [`@skyra/jaro-winkler`](https://www.npmjs.com/package/@skyra/jaro-winkler)

**Comment by almostSouji** [comment]
This might be easier to do now since node.js refactored their docs page. They use a third-party search provider, [orama](https://askorama.ai/); should work similar to meili/algolia approach-wise
