### ISSUE TITLE
Feature: Versioned tags

### ISSUE THREAD

**Issue by JPBM135** [discordjs/discord-utils-bot#125]
Allow tags to be versioned so thay can present different results depending on the version choosed

### Suggested structure:

```toml
[tag-name]
keywords = ["tag-name", "alias", "another-alias"]
content = """
Put your tag content here!
"""
content-v13= """
Optional 
Put your tag content here!
"""
```

If `content-v13` is not present, it will use the normal content for both versions

Probably needs a better and and more expandable implementation!

**Comment by jaw0r3k** [comment]
Is it really needed?

**Comment by JPBM135** [comment]
The fact that tags are base of support and some times we use tags not designed for that version which may confuse the user more, and this adds the flexibility to fix this.

**Comment by JPBM135** [comment]
But **really** need, I would say No
