### ISSUE TITLE
feat: `discord-developers` tag

### ISSUE THREAD

**Issue by Fyko** [discordjs/discord-utils-bot#127]
I'd like to propose the tag:

Title: `discord-developers`
Keywords: `discord-developers`, `ddevs`, `devsupport`
Content:
```
FAQ about Verification, Game SDK support, and API Announcements.
- <https://discord.gg/discord-developers>
```

**Comment by jaw0r3k** [comment]
api-docs is there

**Comment by almostSouji** [comment]
If you want to add aliases, feel free
