### ISSUE TITLE
Feature: Ephemeral reply option

### ISSUE THREAD

**Issue by anandre** [discordjs/discord-utils-bot#141]
It'd be useful to have an ephemeral option in the docs command, and possibly others, such as mdn, node, etc.  This would let someone use it as a reference for themselves, to check a property, method, or class without having to switch channels and losing focus, or cluttering up a support channel.

It could default to false, so the current functionality remains the same, and this would be an optional use.

**Comment by jaw0r3k** [comment]
Just use them on dm :)

**Comment by anandre** [comment]
> Just use them in dm :)

That's... even worse than going to a bot-command channel to use.
