### ISSUE TITLE
Wrong link for TextBasedChannel

### ISSUE THREAD

**Issue by almostSouji** [discordjs/discord-utils-bot#145]
Prompt `/docs discord-js query: textbasedchannel`
Result link <https://discord.js.org/#/docs/discord.js/stable/interface/TextBasedChannel> leads nowhere, as should be <https://discord.js.org/#/docs/discord.js/stable/typedef/TextBasedChannels>.

Unsure if docs handling/docs link or if solvable at all

**Comment by Jiralite** [comment]
This is what `TextBasedChannel` is: https://github.com/discordjs/discord.js/blob/stable/src/structures/interfaces/TextBasedChannel.js

The link is correct, but this interface is not documented.
