### ISSUE TITLE
feat: support new packages 

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord-utils-bot#152]
as lastly new packages were added 
it would be nice if some of them had a docs command
like rest or core

**Comment by almostSouji** [comment]
Working on a move towards to the new docs approach with planetscale at <https://github.com/discordjs/discord-utils-bot/tree/refactor-docs>

**Comment by almostSouji** [comment]
I have now moved the prod /docs command to use the new docs including subcommand for all packages and support for all versions present in the database.
