### ISSUE TITLE
Discord api types autocomplete displays triple choices

### ISSUE THREAD

**Issue by jaw0r3k** [discordjs/discord-utils-bot#183]
![image](https://github.com/discordjs/discord-utils-bot/assets/76836550/6d840098-6fc8-488a-91c0-40ff6c78f146)

Looks like a bug

**Comment by almostSouji** [comment]
I suspect that leads to different subheadings or similar, but will have a look into either deduping these or being more verbose with the name

**Comment by almostSouji** [comment]
The deduping based on object ID was insufficient, as it included some prefixes resulting in the same generated URL. However, these results are not returned from observing the docs website's behavior, so I am not sure what exactly is happening there.

> [!NOTE]  
> I switched to a hierarchy-based approach and that seems to work well (after all this is what categorizes the hit)
We will now have to observe if this breaks other Algolia commands, but logic-wise I cannot yet see an issue with that approach.
