### ISSUE TITLE
Search results that require a selection post their response as a followUp to an ephemeral message

### ISSUE THREAD

**Issue by ImRodry** [discordjs/discord-utils-bot#47]
Whenever we make a search using /docs, for example, and we get an ephemeral reply with a select menu in the response, upon selecting the result, the bot will respond with a follow up reply, which seems ok to the author of the command but actually displays as a reply to a deleted message for other users, since the referenced message is ephemeral. This doesn't make much sense so I believe the bot should send a regular text message instead, and not use the webhook at all.

**Comment by GodderE2D** [comment]
> This doesn't make much sense so I believe the bot should send a regular text message instead

This is not possible since there is no bot user that could send a message in the channel.

You would need to create a new webhook, write to that webhook, and possibly have webhooks for every channel the command could be ran in.

I think that's too much work for a not-so-important "bug".

**Comment by almostSouji** [comment]
Unless they introduce a way to "publish" ephemeral messages so everyone can read them, there is no alternative to this. The UX isn't very nice, but the nicest I can do at the moment without making the selection a public message in the first place (which is arguably worse)

**Comment by ImRodry** [comment]
Oh I wasn’t aware there was no bot user, oops
That makes sense then, sorry for bothering
